### ISSUE TITLE
无法加载资源文件

### ISSUE THREAD

**Issue by PackageInstaller** [xi-yue-233/nonebot-plugin-p5generator#1]
系统：Arch linux
Bot：zhenxun_bot
问题描述：git pull的插件，已提前将 **p5generator** 文件夹移动至 **/home/Neko/Bot/zhenxun_bot/data** 目录下（没有资源文件缺失），启动bot后发送 **p5预告信测试** 指令后出现如下报错

![image](https://github.com/xi-yue-233/nonebot-plugin-p5generator/assets/80018096/aad5c5f7-4dba-406e-923f-621ca15adf74)

**Comment by xi-yue-233** [comment]
看了一下，貌似是因为Linux和windows对于路径识别不同导致的，我windows系统下进行的插件编写，同时在windows server上进行的插件部署，就没有问题，没有考虑到Linux的使用，稍后我看看能不能修改一下

**Comment by PackageInstaller** [comment]
好的，有劳了

**Comment by xi-yue-233** [comment]
已在[#1ebbce3dae66513f556eb4d363c8639303ccd8da](https://github.com/xi-yue-233/nonebot-plugin-p5generator/commit/1ebbce3dae66513f556eb4d363c8639303ccd8da) 尝试修复

**Comment by PackageInstaller** [comment]
ok了
