### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by Suica0w0** [xi-yue-233/nonebot-plugin-p5generator#2]
绘制背景色块时可以加上outline来添加外边框
![图片](https://github.com/xi-yue-233/nonebot-plugin-p5generator/assets/21064134/edf76bfc-9f7c-4ac8-90c4-d01f6ebfec53)

**Comment by xi-yue-233** [comment]
可以看看效果吗？效果好得话可以提个pr，主要是我为了仿游戏里面的预告信从报纸上剪下来的效果，所以就没有加这个

**Comment by Suica0w0** [comment]
效果如图
![QQ图片20230517234901](https://github.com/xi-yue-233/nonebot-plugin-p5generator/assets/21064134/02dedd85-363f-4554-9ba4-db2fb62c9733)
我看http://yuluoluo.top/p5cc这个生成器是这样的，感觉视觉效果会好一些

**Comment by xi-yue-233** [comment]
> 效果如图 ![QQ图片20230517234901](https://user-images.githubusercontent.com/21064134/239007319-02dedd85-363f-4554-9ba4-db2fb62c9733.jpg) 我看[http://yuluoluo.top/p5cc这个生成器是这样的，感觉视觉效果会好一些](http://yuluoluo.top/p5cc%E8%BF%99%E4%B8%AA%E7%94%9F%E6%88%90%E5%99%A8%E6%98%AF%E8%BF%99%E6%A0%B7%E7%9A%84%EF%BC%8C%E6%84%9F%E8%A7%89%E8%A7%86%E8%A7%89%E6%95%88%E6%9E%9C%E4%BC%9A%E5%A5%BD%E4%B8%80%E4%BA%9B)

这个看起来更像p5r风格的ui，可否提交一份pr呢？

**Comment by xi-yue-233** [comment]
已经merge了，现在输入p5预告信还是生成之前的内容，输入p5ui可以生成这个风格的图片
